//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador_AdopcionMascotas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADOPCION
    {
        public long CODADOPCION { get; set; }
        public long ANIMAL { get; set; }
        public long INTERESADO { get; set; }
        public System.DateTime FEC_ADOP { get; set; }
    
        public virtual ANIMAL ANIMAL1 { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
