//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador_AdopcionMascotas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAZAANIMAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RAZAANIMAL()
        {
            this.ANIMAL = new HashSet<ANIMAL>();
        }
    
        public long CODTIPO { get; set; }
        public long CODRAZA { get; set; }
        public string DESC_RAZA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANIMAL> ANIMAL { get; set; }
        public virtual TIPOANIMAL TIPOANIMAL { get; set; }
    }
}
