//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador_AdopcionMascotas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.ADOPCION = new HashSet<ADOPCION>();
        }

        public USUARIO(bool eSTADO)
        {
            ESTADO = eSTADO;
        }

        [DisplayName("Código de Usuario")]
        public long CODUSUARIO { get; set; }
        [DisplayName("Nombres")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Campo obligatorio")]
        [MaxLength(100, ErrorMessage = "Ingresar maximo hasta 100 caracteres")]
        public string NOMBRES { get; set; }
        [DisplayName("Apellidos")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Campo obligatorio")]
        [MaxLength(100, ErrorMessage = "Ingresar maximo hasta 100 caracteres")]
        public string APELLIDOS { get; set; }
        [DisplayName("Fecha de nacimiento")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Campo obligatorio")]
        public System.DateTime FEC_NAC { get; set; }
        [DisplayName("DNI")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Campo obligatorio")]
        [RegularExpression("^[0-9]{8}$", ErrorMessage = "DNI debe contener 8 digitos numericos")]
        public string DNI { get; set; }
        [DisplayName("Sexo")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Campo obligatorio")]

        public string SEXO { get; set; }
        [DisplayName("Dirección")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Campo obligatorio")]
        public string DIRECCION { get; set; }
        [DisplayName("E-mail")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Campo obligatorio")]
        [MaxLength(200, ErrorMessage = "Ingresar maximo hasta 200 caracteres")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Ingrese una dirección de E-mail válida")]
        public string EMAIL { get; set; }
        [DisplayName("Teléfono")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Campo obligatorio")]
        [MaxLength(20, ErrorMessage = "Ingresar maximo hasta 20 caracteres")]
        [RegularExpression("^[0-9]{9,15}$", ErrorMessage = "Ingrese un numero telefonico")]
        public string TELEFONO { get; set; }
        [DisplayName("Id de Usuario")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Campo obligatorio")]
        [MaxLength(100, ErrorMessage = "Ingresar maximo hasta 100 caracteres")]
        public string IDLOGIN { get; set; }
        [DisplayName("Contraseña")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Campo obligatorio")]
        [RegularExpression("^[0-9a-zA-Z]{8,100}$", ErrorMessage = "Minimo 8 caracteres y máximo 100 caracteres")]
        public string PASS { get; set; }
        public bool ESTADO { get; set; }
        public string FOTO { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADOPCION> ADOPCION { get; set; }
    }
}
