USE MASTER
GO
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME LIKE 'BD_SISTEMA_ADOPCION') DROP DATABASE BD_SISTEMA_ADOPCION
GO
CREATE DATABASE BD_SISTEMA_ADOPCION
GO
USE BD_SISTEMA_ADOPCION
GO


----------------------------------------------------------------------------------

CREATE TABLE USUARIO (
CODUSUARIO BIGINT PRIMARY KEY IDENTITY,
NOMBRES VARCHAR(100) NOT NULL,
APELLIDOS VARCHAR(100) NOT NULL,
FEC_NAC DATE NOT NULL,
DNI CHAR(8) NOT NULL,
SEXO INT NOT NULL,
DIRECCION VARCHAR(200) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
TELEFONO VARCHAR(20) NOT NULL,
IDLOGIN VARCHAR(100) NOT NULL,
PASS VARCHAR(100) NOT NULL,
ESTADO BIT NOT NULL DEFAULT 1,
FOTO VARCHAR(100) NOT NULL
)
GO
INSERT INTO USUARIO VALUES ('JOSE', 'ALCANTARA', '1999/06/14', '14768532', 1, 'AV CANADA 3151 SAN BORJA', 'JOSEALCANTARA@HOTMAIL.COM', '996145387', 'JOALC', '1234654', DEFAULT, 'IMG000001.JPG')
INSERT INTO USUARIO VALUES ('LUIS', 'GONZALES', '1993/01/22', '15666522', 1, 'AV COLONIAL 2050 CERCADO DE LIMA', 'LUISGONZALES@HOTMAIL.COM', '992146321', 'LUCHO', '69531478', DEFAULT, 'IMG000002.JPG')
INSERT INTO USUARIO VALUES ('MARIA', 'RODRIGUEZ', '1994/07/30', '15842236', 2, 'AV LA MAR 310 FREMTE A PLAZA SAN MIGUEL', 'MARIARODRIGUEZ@HOTMAIL.COM', '992475831', 'LUOH', '159585666', DEFAULT, 'IMG000003.JPG')
INSERT INTO USUARIO VALUES ('ANGELA', 'HUAHUA', '1989/03/06', '65458416', 2, 'AV BRASIL 4389 MAGDALENA DEL MAR', 'ANGELAHUAHUA@HOTMAIL.COM', '991876543', 'ANGELA123', '1234514', DEFAULT, 'IMG000004.JPG')
INSERT INTO USUARIO VALUES ('RIAS', 'GREMORY', '1992/06/30', '14768532', 1, 'AV PARDO 322 MIRAFLORES FRENTE EMBAJADA DE BRASIL', 'LEGREMORY@HOTMAIL.COM', '992654494', 'DEVIL69', '4546552545', DEFAULT, 'IMG000005.JPG')
SELECT * FROM USUARIO
GO

----------------------------------------------------------------------------------
CREATE TABLE ANIMAL(

CODANIMAL BIGINT PRIMARY KEY IDENTITY,
NOMBRE VARCHAR(100) NOT NULL,
ESTADO INT NOT NULL DEFAULT 1,
EDAD INT NOT NULL,
SEXO INT NOT NULL,
PESO NUMERIC(19,6),
TAMAÑO INT NOT NULL,
DESCRIPCION VARCHAR(200) NOT NULL,
TIPO BIGINT NOT NULL,
RAZA BIGINT NOT NULL,
DUEÑO BIGINT NOT NULL,
FOTO VARCHAR(100) NOT NULL
)
GO
INSERT INTO ANIMAL(NOMBRE,EDAD,SEXO,PESO,TAMAÑO,DESCRIPCION,TIPO,RAZA,DUEÑO,FOTO) VALUES
('RUFUS',0,1,0,3,'',1,1,1,'IMG000001.JPG'),
('MICAELA',0,2,0,2,'',1,4,1,'IMG000002.JPG'),
('SACHA',0,2,0,2,'',2,3,1,'IMG000003.JPG'),
('KALIFA',0,1,0,1,'',2,2,2,'IMG000004.JPG'),
('ZEUS',0,1,0,3,'',2,4,2,'IMG000005.JPG'),
('MIMI',0,2,0,2,'',2,1,2,'IMG000006.JPG'),
('POCHO',0,1,0,2,'',1,4,3,'IMG000007.JPG'),
('HUM',0,1,0,1,'',2,3,3,'IMG000008.JPG'),
('LALA',0,2,0,1,'',1,8,3,'IMG000009.JPG'),
('FITO',0,1,0,2,'',1,4,4,'IMG000010.JPG'),
('MICHI',0,2,0,2,'',2,9,4,'IMG000011.JPG'),
('MICHITA',0,2,0,1,'',2,1,4,'IMG000012.JPG'),
('PACHO',0,1,0,1,'',2,6,5,'IMG000013.JPG'),
('RURU',0,2,0,1,'',1,5,5,'IMG000014.JPG'),
('YURI',0,2,0,1,'',1,8,2,'IMG000015.JPG'),
('PELUCHIN',0,1,0,1,'',1,6,5,'IMG000016.JPG')
SELECT * FROM ANIMAL
GO


----------------------------------------------------------------------------------
CREATE TABLE TIPOANIMAL(
CODTIPO BIGINT PRIMARY KEY IDENTITY,
DESC_TIPO VARCHAR(100) NOT NULL
)
GO
INSERT INTO TIPOANIMAL(DESC_TIPO) VALUES ('PERRO'),('GATO'),('PAJARO'),('ROEDORES'),('REPTILES')
SELECT * FROM TIPOANIMAL
GO



----------------------------------------------------------------------------------
CREATE TABLE RAZAANIMAL(
CODTIPO BIGINT NOT NULL,
CODRAZA BIGINT NOT NULL,
DESC_RAZA VARCHAR (100) NOT NULL,
PRIMARY KEY (CODTIPO,CODRAZA)
)
INSERT INTO RAZAANIMAL VALUES
(1,1,'#NO DETERMINADA'),
(1,2,'COBRADOR DE PELO LISO'),
(1,3,'DOBERMAN'),
(1,4,'PEQUINES'),
(1,5,'POODLE'),
(1,6,'HUSKY SIBERIANO'),
(1,7,'LABRADOR RETRIEVER'),
(1,8,'PUG'),
(1,9,'BEAGLE'),
(1,10,'PITBULL'),
(2,1,'#NO DETERMINADA'),
(2,2,'SCOTTISH FOLD'),
(2,3,'SIAMES'),
(2,4,'GATO CURL AMERICANO'),
(2,5,'MAINE COON'),
(2,6,'GATO PERSA'),
(2,7,'BENGALÍ'),
(2,8,'ORIENTAL DE PELO LARGO'),
(2,9,'LAPERM'),
(2,10,'ABISINIO')
SELECT * FROM RAZAANIMAL
GO



----------------------------------------------------------------------------------
CREATE TABLE ADOPCION(
CODADOPCION BIGINT PRIMARY KEY IDENTITY(1,1),
ANIMAL BIGINT NOT NULL,
INTERESADO BIGINT NOT NULL,
FEC_ADOP DATETIME NOT NULL
)
INSERT INTO ADOPCION VALUES(3,3,'20191108 16:50')
INSERT INTO ADOPCION VALUES(2,5,'20191121 12:08')
SELECT * FROM ADOPCION
GO


----------------------------------------------------------------------------------
CREATE TABLE INTERES(
ANIMAL	BIGINT	NOT NULL,
INTERESADO	BIGINT	NOT NULL,
ESTADO	INT	NOT NULL DEFAULT 1,
FEC_INI	DATETIME NOT NULL DEFAULT GETDATE(),
FEC_ATE	DATETIME NOT NULL DEFAULT '19000101',
FEC_RESP DATETIME NOT NULL DEFAULT '19000101',
PRIMARY KEY (ANIMAL,INTERESADO)
)
INSERT INTO INTERES(ANIMAL,INTERESADO) VALUES (1,3),(1,4),(1,5),(2,2),(2,3),(2,4),(3,2),(3,4),(3,3),(3,5),(4,1),(5,1),(6,1),(7,1),(8,1)
SELECT * FROM INTERES
GO



----------------------------------------------------------------


ALTER TABLE ANIMAL ADD CONSTRAINT FK_ANIMAL_TIPO_RAZA FOREIGN KEY (TIPO,RAZA) REFERENCES RAZAANIMAL(CODTIPO,CODRAZA)
ALTER TABLE RAZAANIMAL ADD CONSTRAINT FK_RAZA_TIPO FOREIGN KEY (CODTIPO) REFERENCES TIPOANIMAL(CODTIPO)
ALTER TABLE ADOPCION ADD CONSTRAINT FK_ADOP_ANIMAL FOREIGN KEY (ANIMAL) REFERENCES ANIMAL(CODANIMAL)
ALTER TABLE ADOPCION ADD CONSTRAINT FK_ADOP_INTERESADO FOREIGN KEY (INTERESADO) REFERENCES USUARIO(CODUSUARIO)
ALTER TABLE INTERES ADD CONSTRAINT FK_INTERES_ANIMAL FOREIGN KEY (ANIMAL) REFERENCES ANIMAL(CODANIMAL)
ALTER TABLE INTERES ADD CONSTRAINT FK_INTERES_INTERESADO FOREIGN KEY (INTERESADO) REFERENCES USUARIO(CODUSUARIO)


---------------------------------PROCEDIMIENTOS ALMACENADOS-------------------------------
DROP PROC IF EXISTS SP_REGISTRAR_USUARIO
GO
CREATE PROC SP_REGISTRAR_USUARIO
@NOMBRES VARCHAR(100),
 @APELLIDOS VARCHAR(100),
 @FEC_NAC DATE,
 @DNI CHAR(8),
 @SEXO INT,
 @DIRECCION VARCHAR(200),
 @EMAIL VARCHAR(100),
 @TELEFONO VARCHAR(20),
 @IDLOGIN VARCHAR(100),
 @PASS VARCHAR(100),
 @FOTO VARCHAR(100)
 AS
INSERT INTO [DBO].[USUARIO]
           ([NOMBRES]
           ,[APELLIDOS]
           ,[FEC_NAC]
           ,[DNI]
           ,[SEXO]
           ,[DIRECCION]
           ,[EMAIL]
           ,[TELEFONO]
           ,[IDLOGIN]
           ,[PASS]
		   ,[FOTO]
		  )
     VALUES(
           @NOMBRES, 
           @APELLIDOS, 
           @FEC_NAC,
           @DNI, 
           @SEXO, 
           @DIRECCION, 
           @EMAIL, 
           @TELEFONO, 
           @IDLOGIN, 
           @PASS,
		   @FOTO)
GO
EXEC SP_REGISTRAR_USUARIO 'JESUS','GAMEZ','19901220','73580887',1,'AV COLONIAL 340 FRENTE A PLAZA VEA','','','JGAMEZ','12341234',''

DROP PROCEDURE IF EXISTS SP_EDITAR_USUARIO
GO
CREATE PROCEDURE SP_EDITAR_USUARIO
@CODUSUARIO BIGINT,
@DIRECCION VARCHAR(200),
@EMAIL VARCHAR(100),
@TELEFONO VARCHAR(20),
@IDLOGIN VARCHAR(100),
@PASS VARCHAR(100)
AS
UPDATE [DBO].[USUARIO]
   SET [DIRECCION] = @DIRECCION
      ,[EMAIL] =     @EMAIL
      ,[TELEFONO] =  @TELEFONO
      ,[IDLOGIN] =   @IDLOGIN
      ,[PASS] =      @PASS
 WHERE [CODUSUARIO]=@CODUSUARIO
GO

EXEC SP_EDITAR_USUARIO 6,'AV COLONIAL 340 FRENTE A PLAZA VEA','JGAMEZ@GMAIL.COM','','JGAMEZ','12341234'


DROP PROC IF EXISTS SP_REGISTRAR_ANIMAL
GO
CREATE PROC SP_REGISTRAR_ANIMAL
@NOMBRE VARCHAR(100),      
@EDAD INT,
@SEXO INT,
@PESO NUMERIC(19,6),
@TAMAÑO INT,
@DESCRIPCION VARCHAR(200),
@TIPO BIGINT,
@RAZA BIGINT, 
@DUEÑO BIGINT,      
@FOTO VARCHAR(100)
AS
INSERT INTO [DBO].[ANIMAL]
           ([NOMBRE]
           ,[EDAD]
           ,[SEXO]
           ,[PESO]
           ,[TAMAÑO]
           ,[DESCRIPCION]
           ,[TIPO]
           ,[RAZA]
		   ,[DUEÑO]
           ,[FOTO])
     VALUES(
           @NOMBRE,           
           @EDAD, 
           @SEXO, 
           @PESO, 
           @TAMAÑO, 
           @DESCRIPCION, 
           @TIPO, 
           @RAZA, 
		   @DUEÑO,        
           @FOTO)
GO

EXECUTE SP_REGISTRAR_ANIMAL 'PEQUEÑO',0,1,0,2,'',1,10,6,''


DROP PROC IF EXISTS SP_EDITAR_ANIMAL
GO 
CREATE PROC SP_EDITAR_ANIMAL
@CODANIMAL BIGINT,
@NOMBRE VARCHAR(100),   
@EDAD INT,
@SEXO INT,
@PESO NUMERIC(19,6),
@TAMAÑO INT,
@DESCRIPCION VARCHAR(200),
@RAZA BIGINT,
@FOTO VARCHAR(100)
AS
UPDATE [DBO].[ANIMAL]
   SET [NOMBRE] =		@NOMBRE, 
      [EDAD] =			@EDAD, 
      [SEXO] =			@SEXO, 
      [PESO] =			@PESO, 
      [TAMAÑO] =		@TAMAÑO, 
      [DESCRIPCION] =	@DESCRIPCION, 
      [RAZA] =			@RAZA, 
      [FOTO] =			@FOTO
 WHERE CODANIMAL=@CODANIMAL
GO

EXEC SP_EDITAR_ANIMAL 17,'PEQUEÑO',2,1,23.60,2,'PERRO MUY AMABLE',10,'IMG000017.JPG'
GO

DROP VIEW IF EXISTS VW_ANIMAL_TUNEADO
GO
CREATE VIEW VW_ANIMAL_TUNEADO 
AS
SELECT A.CODANIMAL,
A.NOMBRE,
A.ESTADO AS 'CODESTADO', 
CASE WHEN A.ESTADO = 1 THEN
'NO ADOPTADO'
WHEN A.ESTADO = 2 THEN
'EN PROCESO DE ADOPCION'
WHEN A.ESTADO = 3 THEN
'ADOPTADO'
END AS ESTADO,
CAST(A.EDAD AS VARCHAR) + ' AÑOS' AS EDAD,
CASE WHEN A.SEXO = 1 THEN
'MACHO'
WHEN A.SEXO = 2 THEN
'HEMBRA'
END AS SEXO,
CAST(A.PESO AS VARCHAR) + ' KG' AS PESO,
CASE WHEN A.TAMAÑO = 1 THEN
'PEQUEÑO'
WHEN A.TAMAÑO = 2 THEN
'MEDIANO'
WHEN A.TAMAÑO = 3 THEN
'GRANDE'
END AS TAMAÑO,
A.DESCRIPCION,
A.TIPO,
T.DESC_TIPO,
A.RAZA,
R.DESC_RAZA,
U.CODUSUARIO,
U.NOMBRES +' '+ U.APELLIDOS AS DUEÑO,
A.FOTO FROM ANIMAL A
INNER JOIN TIPOANIMAL T ON A.TIPO = T.CODTIPO
INNER JOIN RAZAANIMAL R ON A.RAZA = R.CODRAZA AND A.TIPO = R.CODTIPO
INNER JOIN USUARIO U ON U.CODUSUARIO = A.DUEÑO
GO

SELECT * FROM VW_ANIMAL_TUNEADO
GO

DROP PROC IF EXISTS SP_AUTOGENEREA_ANIMAL
GO
CREATE PROC SP_AUTOGENEREA_ANIMAL
AS
SELECT TOP 1 CODANIMAL+1 FROM ANIMAL ORDER BY CODANIMAL DESC
GO

EXEC SP_AUTOGENEREA_ANIMAL



DROP PROC IF EXISTS SP_VER_INTERESADOS
GO 
CREATE PROC SP_VER_INTERESADOS
@CODANIMAL BIGINT
AS
SELECT U.CODUSUARIO, U.NOMBRES+' '+U.APELLIDOS AS 'INTERESADO',FORMAT(I.FEC_INI,'dd/MM/yyyy hh:mm:ss tt') AS 'FECHAINTERES' FROM USUARIO AS U  JOIN INTERES AS I ON U.CODUSUARIO=I.INTERESADO WHERE I.ANIMAL=@CODANIMAL
GO

EXEC SP_VER_INTERESADOS 1
EXEC SP_VER_INTERESADOS 2
EXEC SP_VER_INTERESADOS 3
EXEC SP_VER_INTERESADOS 4

DROP VIEW IF EXISTS VW_USUARIO_TUNEADO
GO
CREATE VIEW VW_USUARIO_TUNEADO AS 
SELECT U.CODUSUARIO,U.NOMBRES+' ' +U.APELLIDOS AS 'NOMBRES',FORMAT(U.FEC_NAC,'dd/MM/yyyy') as 'FEC_NAC',U.DNI,CASE WHEN U.SEXO=1 THEN 'HOMBRE' ELSE 'MUJER' END AS 'SEXO',U.DIRECCION,U.EMAIL,U.TELEFONO,U.FOTO,CASE WHEN U.ESTADO=1 THEN 'ACTIVO' ELSE 'INACTIVO' END AS 'ESTADO' FROM USUARIO AS U
GO

SELECT * FROM VW_USUARIO_TUNEADO


DROP PROC IF EXISTS SP_VER_MASCOTAS_FAVORITAS
GO
CREATE PROC SP_VER_MASCOTAS_FAVORITAS
@CODUSUARIO BIGINT
AS
SELECT * FROM VW_ANIMAL_TUNEADO where CODANIMAL in (SELECT ANIMAL from INTERES where INTERESADO=@CODUSUARIO)
GO

EXEC SP_VER_MASCOTAS_FAVORITAS 3



--QUIERO QUE ME SALGAN SOLO LOS ANIMALES QUE NO SON MIOS, QUE NO ESTAN ADOPTADOS AUN Y A LOS QUE TODAVIA NO LES DI NINGUN INTERES
DROP PROC IF EXISTS SP_VER_MASCOTAS_INDEX_USUARIO
GO 
CREATE PROC SP_VER_MASCOTAS_INDEX_USUARIO
@CODUSUARIO BIGINT
AS 
IF @CODUSUARIO=0 
BEGIN
SELECT * FROM VW_ANIMAL_TUNEADO WHERE CODESTADO IN (1,2)
END
ELSE
BEGIN
SELECT * FROM VW_ANIMAL_TUNEADO WHERE CODUSUARIO<>@CODUSUARIO AND CODESTADO IN (1,2) AND CODANIMAL NOT IN (SELECT ANIMAL FROM INTERES WHERE INTERESADO=@CODUSUARIO)
END 
GO

EXEC SP_VER_MASCOTAS_INDEX_USUARIO 0
EXEC SP_VER_MASCOTAS_INDEX_USUARIO 1
EXEC SP_VER_MASCOTAS_INDEX_USUARIO 2
EXEC SP_VER_MASCOTAS_INDEX_USUARIO 3
EXEC SP_VER_MASCOTAS_INDEX_USUARIO 4
EXEC SP_VER_MASCOTAS_INDEX_USUARIO 5
EXEC SP_VER_MASCOTAS_INDEX_USUARIO 6
GO

--drop proc if exists SP_VER_MASCOTAS_RAZA_TIPO
--go
--CREATE PROC SP_VER_MASCOTAS_RAZA_TIPO
--@TIPO bigINT,
--@RAZA bigINT,
--@CODUSUARIO bigINT
--AS
--begin
--if @raza = 0 and @tipo = 0
--EXEC SP_VER_MASCOTAS_INDEX_USUARIO @CODUSUARIO
--else if @RAZA = 0 and @TIPO <> 0
--SELECT * FROM VW_ANIMAL_TUNEADO WHERE CODESTADO IN (1,2) AND tipo = @TIPO AND CODUSUARIO <> @CODUSUARIO AND CODANIMAL NOT IN (SELECT ANIMAL FROM INTERES WHERE INTERESADO=@CODUSUARIO)
--else
--SELECT * FROM VW_ANIMAL_TUNEADO WHERE CODESTADO IN (1,2) AND tipo = @TIPO AND RAZA = @RAZA AND CODUSUARIO <> @CODUSUARIO AND CODANIMAL NOT IN (SELECT ANIMAL FROM INTERES WHERE INTERESADO=@CODUSUARIO)
--end
--GO
--EXEC SP_VER_MASCOTAS_RAZA_TIPO 2,1,4
--GO


DROP PROC IF EXISTS SP_VER_MASCOTAS_RAZA_TIPO
GO
CREATE PROC SP_VER_MASCOTAS_RAZA_TIPO
@DUEÑO BIGINT,
@TIPO BIGINT,
@RAZA BIGINT
AS
IF @DUEÑO=0 AND @TIPO=0 AND @RAZA=0 
SELECT * FROM VW_ANIMAL_TUNEADO WHERE CODESTADO IN (1,2)
ELSE IF @DUEÑO=0 AND @TIPO=0
SELECT * FROM VW_ANIMAL_TUNEADO WHERE CODESTADO IN (1,2) AND RAZA=@RAZA
ELSE IF @DUEÑO=0 AND @RAZA=0
SELECT * FROM VW_ANIMAL_TUNEADO WHERE CODESTADO IN (1,2) AND TIPO=@TIPO
ELSE IF @DUEÑO=0
SELECT * FROM VW_ANIMAL_TUNEADO WHERE CODESTADO IN (1,2) AND TIPO=@TIPO AND RAZA=@RAZA
ELSE IF @TIPO=0 AND @RAZA=0
SELECT * FROM VW_ANIMAL_TUNEADO WHERE CODUSUARIO<>@DUEÑO AND CODESTADO IN (1,2)  AND CODANIMAL NOT IN (SELECT ANIMAL FROM INTERES WHERE INTERESADO=@DUEÑO)
ELSE IF @TIPO=0
SELECT * FROM VW_ANIMAL_TUNEADO WHERE CODUSUARIO<>@DUEÑO AND CODESTADO IN (1,2) AND RAZA=@RAZA AND CODANIMAL NOT IN (SELECT ANIMAL FROM INTERES WHERE INTERESADO=@DUEÑO)
ELSE IF @RAZA=0
SELECT * FROM VW_ANIMAL_TUNEADO WHERE CODUSUARIO<>@DUEÑO AND CODESTADO IN (1,2) AND TIPO=@TIPO AND CODANIMAL NOT IN (SELECT ANIMAL FROM INTERES WHERE INTERESADO=@DUEÑO)
ELSE
SELECT * FROM VW_ANIMAL_TUNEADO WHERE CODUSUARIO<>@DUEÑO AND CODESTADO IN (1,2) AND TIPO=@TIPO AND RAZA=@RAZA AND CODANIMAL NOT IN (SELECT ANIMAL FROM INTERES WHERE INTERESADO=@DUEÑO)
GO



EXEC SP_VER_MASCOTAS_RAZA_TIPO 0,0,0
EXEC SP_VER_MASCOTAS_RAZA_TIPO 0,0,6
EXEC SP_VER_MASCOTAS_RAZA_TIPO 0,1,0
EXEC SP_VER_MASCOTAS_RAZA_TIPO 0,1,6
EXEC SP_VER_MASCOTAS_RAZA_TIPO 1,0,0
EXEC SP_VER_MASCOTAS_RAZA_TIPO 1,0,6
EXEC SP_VER_MASCOTAS_RAZA_TIPO 1,1,0
EXEC SP_VER_MASCOTAS_RAZA_TIPO 1,1,6
GO